"""Changes on fields on new JSON 

Revision ID: 02a4b4e804b4
Revises: 8b88d473c772
Create Date: 2017-10-06 15:48:26.030582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a4b4e804b4'
down_revision = '8b88d473c772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_company_history', sa.Column('cloud_results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_company_history', 'cloud_results')
    # ### end Alembic commands ###
