"""Company parameters

Revision ID: 60b284f65f89
Revises: 7d9dde8fc1b5
Create Date: 2018-08-16 16:27:13.790552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60b284f65f89'
down_revision = '7d9dde8fc1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_parameters',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_parameters_company_id'), 'company_parameters', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_parameters_created_at'), 'company_parameters', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_parameters_id'), 'company_parameters', ['id'], unique=True)
    op.create_index(op.f('ix_company_parameters_key'), 'company_parameters', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_parameters_key'), table_name='company_parameters')
    op.drop_index(op.f('ix_company_parameters_id'), table_name='company_parameters')
    op.drop_index(op.f('ix_company_parameters_created_at'), table_name='company_parameters')
    op.drop_index(op.f('ix_company_parameters_company_id'), table_name='company_parameters')
    op.drop_table('company_parameters')
    # ### end Alembic commands ###
