"""Added partial field to succes table

Revision ID: 74158fa98be1
Revises: 02a4b4e804b4
Create Date: 2017-10-10 08:46:10.794199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74158fa98be1'
down_revision = '02a4b4e804b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_company_history', sa.Column('partial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_company_history', 'partial')
    # ### end Alembic commands ###
