"""change_lengt_of_models

Revision ID: 7d9dde8fc1b5
Revises: 89e5084fc441
Create Date: 2018-04-26 14:45:06.318852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9dde8fc1b5'
down_revision = '89e5084fc441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cloud_company', 'company_name',
                    existing_type=sa.VARCHAR(length=75),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
