"""model_statistic changes

Revision ID: 89e5084fc441
Revises: 5244e47cbd5a
Create Date: 2017-12-20 15:39:44.257893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e5084fc441'
down_revision = '5244e47cbd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_statistic_api_elastic_hash', table_name='company_statistic')
    op.drop_column('company_statistic', 'api_elastic_hash')
    op.drop_column('company_statistic', 'elastic_hash_deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_statistic', sa.Column('elastic_hash_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('company_statistic', sa.Column('api_elastic_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_company_statistic_api_elastic_hash', 'company_statistic', ['api_elastic_hash'], unique=False)
    # ### end Alembic commands ###
