"""Defualt log default delete false

Revision ID: 9a953e6ff8dd
Revises: e9b211036e64
Create Date: 2017-09-05 10:34:27.784166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a953e6ff8dd'
down_revision = 'e9b211036e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_export_history', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_export_history', 'deleted')
    # ### end Alembic commands ###
