"""New field on export data

Revision ID: a192a933f28e
Revises: aab5244a7405
Create Date: 2017-10-13 08:23:02.287086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a192a933f28e'
down_revision = 'aab5244a7405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_export_history', sa.Column('export_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_export_history', 'export_data')
    # ### end Alembic commands ###
