"""Removed date from and date to

Revision ID: aab5244a7405
Revises: cf5dca780ec8
Create Date: 2017-10-11 14:49:17.636818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab5244a7405'
down_revision = 'cf5dca780ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_export_history_date_from', table_name='company_export_history')
    op.drop_index('ix_company_export_history_date_to', table_name='company_export_history')
    op.drop_column('company_export_history', 'date_to')
    op.drop_column('company_export_history', 'date_from')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_export_history', sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('company_export_history', sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=False))
    op.create_index('ix_company_export_history_date_to', 'company_export_history', ['date_to'], unique=False)
    op.create_index('ix_company_export_history_date_from', 'company_export_history', ['date_from'], unique=False)
    # ### end Alembic commands ###
