"""Create database

Revision ID: c96261e08aa4
Revises: dd273900daa9
Create Date: 2021-05-16 01:01:07.684098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c96261e08aa4'
down_revision = 'dd273900daa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_company',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_company_company_id'), 'cloud_company', ['company_id'], unique=True)
    op.create_index(op.f('ix_cloud_company_id'), 'cloud_company', ['id'], unique=False)
    op.create_table('cloud_company_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Integer(), nullable=False),
    sa.Column('elastic_hash', sa.String(length=255), nullable=False),
    sa.Column('data_hash', sa.String(length=255), nullable=False),
    sa.Column('import_data', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('cloud_inserted', sa.Boolean(), nullable=True),
    sa.Column('active_history', sa.Boolean(), nullable=True),
    sa.Column('partial', sa.Boolean(), nullable=True),
    sa.Column('cloud_results', sa.JSON(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_company_history_company_id'), 'cloud_company_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_cloud_company_history_created_at'), 'cloud_company_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_cloud_company_history_data_hash'), 'cloud_company_history', ['data_hash'], unique=False)
    op.create_index(op.f('ix_cloud_company_history_elastic_hash'), 'cloud_company_history', ['elastic_hash'], unique=False)
    op.create_index(op.f('ix_cloud_company_history_file_path'), 'cloud_company_history', ['file_path'], unique=False)
    op.create_index(op.f('ix_cloud_company_history_full_name'), 'cloud_company_history', ['full_name'], unique=False)
    op.create_index(op.f('ix_cloud_company_history_id'), 'cloud_company_history', ['id'], unique=True)
    op.create_index(op.f('ix_cloud_company_history_import_type'), 'cloud_company_history', ['import_type'], unique=False)
    op.create_index(op.f('ix_cloud_company_history_user_id'), 'cloud_company_history', ['user_id'], unique=False)
    op.create_table('cloud_company_process_fail_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Integer(), nullable=False),
    sa.Column('import_error_type', sa.Integer(), nullable=False),
    sa.Column('elastic_hash', sa.String(length=255), nullable=False),
    sa.Column('data_hash', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active_history', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_company_process_fail_history_company_id'), 'cloud_company_process_fail_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_cloud_company_process_fail_history_created_at'), 'cloud_company_process_fail_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_cloud_company_process_fail_history_data_hash'), 'cloud_company_process_fail_history', ['data_hash'], unique=False)
    op.create_index(op.f('ix_cloud_company_process_fail_history_elastic_hash'), 'cloud_company_process_fail_history', ['elastic_hash'], unique=True)
    op.create_index(op.f('ix_cloud_company_process_fail_history_file_path'), 'cloud_company_process_fail_history', ['file_path'], unique=False)
    op.create_index(op.f('ix_cloud_company_process_fail_history_full_name'), 'cloud_company_process_fail_history', ['full_name'], unique=False)
    op.create_index(op.f('ix_cloud_company_process_fail_history_id'), 'cloud_company_process_fail_history', ['id'], unique=True)
    op.create_index(op.f('ix_cloud_company_process_fail_history_import_error_type'), 'cloud_company_process_fail_history', ['import_error_type'], unique=False)
    op.create_index(op.f('ix_cloud_company_process_fail_history_import_type'), 'cloud_company_process_fail_history', ['import_type'], unique=False)
    op.create_index(op.f('ix_cloud_company_process_fail_history_user_id'), 'cloud_company_process_fail_history', ['user_id'], unique=False)
    op.create_table('company_export_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('export_data', sa.JSON(), nullable=True),
    sa.Column('export_type', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('exported', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_export_history_company_id'), 'company_export_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_export_history_created_at'), 'company_export_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_export_history_export_type'), 'company_export_history', ['export_type'], unique=False)
    op.create_index(op.f('ix_company_export_history_file_path'), 'company_export_history', ['file_path'], unique=False)
    op.create_index(op.f('ix_company_export_history_full_name'), 'company_export_history', ['full_name'], unique=False)
    op.create_index(op.f('ix_company_export_history_id'), 'company_export_history', ['id'], unique=True)
    op.create_index(op.f('ix_company_export_history_query_hash'), 'company_export_history', ['query_hash'], unique=False)
    op.create_index(op.f('ix_company_export_history_user_id'), 'company_export_history', ['user_id'], unique=False)
    op.create_table('company_parameters',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_parameters_company_id'), 'company_parameters', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_parameters_created_at'), 'company_parameters', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_parameters_id'), 'company_parameters', ['id'], unique=True)
    op.create_index(op.f('ix_company_parameters_key'), 'company_parameters', ['key'], unique=False)
    op.create_table('company_statistic',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('api_type', sa.String(length=25), nullable=True),
    sa.Column('api_name', sa.String(length=25), nullable=True),
    sa.Column('api_count', sa.BigInteger(), nullable=True),
    sa.Column('date_statistic', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_statistic_api_name'), 'company_statistic', ['api_name'], unique=False)
    op.create_index(op.f('ix_company_statistic_api_type'), 'company_statistic', ['api_type'], unique=False)
    op.create_index(op.f('ix_company_statistic_company_id'), 'company_statistic', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_statistic_created_at'), 'company_statistic', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_statistic_date_statistic'), 'company_statistic', ['date_statistic'], unique=False)
    op.create_index(op.f('ix_company_statistic_id'), 'company_statistic', ['id'], unique=True)
    op.create_table('vend_device_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_pid', sa.String(length=255), nullable=False),
    sa.Column('machine_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('file_timestamp', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('import_filename', sa.String(length=255), nullable=False),
    sa.Column('zip_filename', sa.String(length=255), nullable=False),
    sa.Column('import_type', sa.String(length=255), nullable=False),
    sa.Column('actual_machine', sa.Boolean(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vend_device_history_company_id'), 'vend_device_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_vend_device_history_created_at'), 'vend_device_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_vend_device_history_device_pid'), 'vend_device_history', ['device_pid'], unique=False)
    op.create_index(op.f('ix_vend_device_history_file_timestamp'), 'vend_device_history', ['file_timestamp'], unique=False)
    op.create_index(op.f('ix_vend_device_history_id'), 'vend_device_history', ['id'], unique=False)
    op.create_index(op.f('ix_vend_device_history_import_filename'), 'vend_device_history', ['import_filename'], unique=False)
    op.create_index(op.f('ix_vend_device_history_import_type'), 'vend_device_history', ['import_type'], unique=False)
    op.create_index(op.f('ix_vend_device_history_machine_id'), 'vend_device_history', ['machine_id'], unique=False)
    op.create_index(op.f('ix_vend_device_history_zip_filename'), 'vend_device_history', ['zip_filename'], unique=False)
    op.create_table('vend_fail_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Integer(), nullable=False),
    sa.Column('import_error_type', sa.Integer(), nullable=False),
    sa.Column('elastic_hash', sa.String(length=255), nullable=False),
    sa.Column('main_elastic_hash', sa.String(length=255), nullable=True),
    sa.Column('data_hash', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active_history', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vend_fail_history_company_id'), 'vend_fail_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_vend_fail_history_created_at'), 'vend_fail_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_vend_fail_history_data_hash'), 'vend_fail_history', ['data_hash'], unique=False)
    op.create_index(op.f('ix_vend_fail_history_elastic_hash'), 'vend_fail_history', ['elastic_hash'], unique=True)
    op.create_index(op.f('ix_vend_fail_history_full_name'), 'vend_fail_history', ['full_name'], unique=False)
    op.create_index(op.f('ix_vend_fail_history_id'), 'vend_fail_history', ['id'], unique=True)
    op.create_index(op.f('ix_vend_fail_history_import_error_type'), 'vend_fail_history', ['import_error_type'], unique=False)
    op.create_index(op.f('ix_vend_fail_history_import_type'), 'vend_fail_history', ['import_type'], unique=False)
    op.create_index(op.f('ix_vend_fail_history_main_elastic_hash'), 'vend_fail_history', ['main_elastic_hash'], unique=False)
    op.create_index(op.f('ix_vend_fail_history_user_id'), 'vend_fail_history', ['user_id'], unique=False)
    op.create_table('vend_success_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Integer(), nullable=False),
    sa.Column('elastic_hash', sa.String(length=255), nullable=False),
    sa.Column('data_hash', sa.String(length=255), nullable=False),
    sa.Column('import_data', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('cloud_inserted', sa.Boolean(), nullable=True),
    sa.Column('partial', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('statistics', sa.JSON(), nullable=True),
    sa.Column('cloud_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['cloud_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vend_success_history_company_id'), 'vend_success_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_vend_success_history_created_at'), 'vend_success_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_vend_success_history_data_hash'), 'vend_success_history', ['data_hash'], unique=False)
    op.create_index(op.f('ix_vend_success_history_elastic_hash'), 'vend_success_history', ['elastic_hash'], unique=False)
    op.create_index(op.f('ix_vend_success_history_id'), 'vend_success_history', ['id'], unique=True)
    op.create_index(op.f('ix_vend_success_history_import_type'), 'vend_success_history', ['import_type'], unique=False)
    op.create_index(op.f('ix_vend_success_history_user_id'), 'vend_success_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vend_success_history_user_id'), table_name='vend_success_history')
    op.drop_index(op.f('ix_vend_success_history_import_type'), table_name='vend_success_history')
    op.drop_index(op.f('ix_vend_success_history_id'), table_name='vend_success_history')
    op.drop_index(op.f('ix_vend_success_history_elastic_hash'), table_name='vend_success_history')
    op.drop_index(op.f('ix_vend_success_history_data_hash'), table_name='vend_success_history')
    op.drop_index(op.f('ix_vend_success_history_created_at'), table_name='vend_success_history')
    op.drop_index(op.f('ix_vend_success_history_company_id'), table_name='vend_success_history')
    op.drop_table('vend_success_history')
    op.drop_index(op.f('ix_vend_fail_history_user_id'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_main_elastic_hash'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_import_type'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_import_error_type'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_id'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_full_name'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_elastic_hash'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_data_hash'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_created_at'), table_name='vend_fail_history')
    op.drop_index(op.f('ix_vend_fail_history_company_id'), table_name='vend_fail_history')
    op.drop_table('vend_fail_history')
    op.drop_index(op.f('ix_vend_device_history_zip_filename'), table_name='vend_device_history')
    op.drop_index(op.f('ix_vend_device_history_machine_id'), table_name='vend_device_history')
    op.drop_index(op.f('ix_vend_device_history_import_type'), table_name='vend_device_history')
    op.drop_index(op.f('ix_vend_device_history_import_filename'), table_name='vend_device_history')
    op.drop_index(op.f('ix_vend_device_history_id'), table_name='vend_device_history')
    op.drop_index(op.f('ix_vend_device_history_file_timestamp'), table_name='vend_device_history')
    op.drop_index(op.f('ix_vend_device_history_device_pid'), table_name='vend_device_history')
    op.drop_index(op.f('ix_vend_device_history_created_at'), table_name='vend_device_history')
    op.drop_index(op.f('ix_vend_device_history_company_id'), table_name='vend_device_history')
    op.drop_table('vend_device_history')
    op.drop_index(op.f('ix_company_statistic_id'), table_name='company_statistic')
    op.drop_index(op.f('ix_company_statistic_date_statistic'), table_name='company_statistic')
    op.drop_index(op.f('ix_company_statistic_created_at'), table_name='company_statistic')
    op.drop_index(op.f('ix_company_statistic_company_id'), table_name='company_statistic')
    op.drop_index(op.f('ix_company_statistic_api_type'), table_name='company_statistic')
    op.drop_index(op.f('ix_company_statistic_api_name'), table_name='company_statistic')
    op.drop_table('company_statistic')
    op.drop_index(op.f('ix_company_parameters_key'), table_name='company_parameters')
    op.drop_index(op.f('ix_company_parameters_id'), table_name='company_parameters')
    op.drop_index(op.f('ix_company_parameters_created_at'), table_name='company_parameters')
    op.drop_index(op.f('ix_company_parameters_company_id'), table_name='company_parameters')
    op.drop_table('company_parameters')
    op.drop_index(op.f('ix_company_export_history_user_id'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_query_hash'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_id'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_full_name'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_file_path'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_export_type'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_created_at'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_company_id'), table_name='company_export_history')
    op.drop_table('company_export_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_user_id'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_import_type'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_import_error_type'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_id'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_full_name'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_file_path'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_elastic_hash'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_data_hash'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_created_at'), table_name='cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_process_fail_history_company_id'), table_name='cloud_company_process_fail_history')
    op.drop_table('cloud_company_process_fail_history')
    op.drop_index(op.f('ix_cloud_company_history_user_id'), table_name='cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_history_import_type'), table_name='cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_history_id'), table_name='cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_history_full_name'), table_name='cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_history_file_path'), table_name='cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_history_elastic_hash'), table_name='cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_history_data_hash'), table_name='cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_history_created_at'), table_name='cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_history_company_id'), table_name='cloud_company_history')
    op.drop_table('cloud_company_history')
    op.drop_index(op.f('ix_cloud_company_id'), table_name='cloud_company')
    op.drop_index(op.f('ix_cloud_company_company_id'), table_name='cloud_company')
    op.drop_table('cloud_company')
    # ### end Alembic commands ###
