"""Export history updated at

Revision ID: cf5dca780ec8
Revises: 74158fa98be1
Create Date: 2017-10-11 10:33:10.594825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5dca780ec8'
down_revision = '74158fa98be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_export_history', sa.Column('exported', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_export_history', 'exported')
    # ### end Alembic commands ###
