"""Change on model export_history

Revision ID: e9b211036e64
Revises: 928eb06f6e8f
Create Date: 2017-09-04 13:41:31.702273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b211036e64'
down_revision = '928eb06f6e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_export_history', sa.Column('date_from', sa.Date(), nullable=False))
    op.add_column('company_export_history', sa.Column('date_to', sa.Date(), nullable=False))
    op.add_column('company_export_history', sa.Column('export_type', sa.Integer(), nullable=True))
    op.alter_column('company_export_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_company_export_history_date_from'), 'company_export_history', ['date_from'], unique=False)
    op.create_index(op.f('ix_company_export_history_date_to'), 'company_export_history', ['date_to'], unique=False)
    op.create_index(op.f('ix_company_export_history_export_type'), 'company_export_history', ['export_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_export_history_export_type'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_date_to'), table_name='company_export_history')
    op.drop_index(op.f('ix_company_export_history_date_from'), table_name='company_export_history')
    op.alter_column('company_export_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('company_export_history', 'export_type')
    op.drop_column('company_export_history', 'date_to')
    op.drop_column('company_export_history', 'date_from')
    # ### end Alembic commands ###
